// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockToEnver creates a new instance of MockToEnver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToEnver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToEnver {
	mock := &MockToEnver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToEnver is an autogenerated mock type for the ToEnver type
type MockToEnver struct {
	mock.Mock
}

type MockToEnver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToEnver) EXPECT() *MockToEnver_Expecter {
	return &MockToEnver_Expecter{mock: &_m.Mock}
}

// ToEnv provides a mock function for the type MockToEnver
func (_mock *MockToEnver) ToEnv() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToEnv")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToEnver_ToEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToEnv'
type MockToEnver_ToEnv_Call struct {
	*mock.Call
}

// ToEnv is a helper method to define mock.On call
func (_e *MockToEnver_Expecter) ToEnv() *MockToEnver_ToEnv_Call {
	return &MockToEnver_ToEnv_Call{Call: _e.mock.On("ToEnv")}
}

func (_c *MockToEnver_ToEnv_Call) Run(run func()) *MockToEnver_ToEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToEnver_ToEnv_Call) Return(strings []string, err error) *MockToEnver_ToEnv_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockToEnver_ToEnv_Call) RunAndReturn(run func() ([]string, error)) *MockToEnver_ToEnv_Call {
	_c.Call.Return(run)
	return _c
}
