version: 1

backends:
  restic:
    enable: true
  rsync:
    enable: true

destinations:
  local:
    backend: rsync
    options:
      destination-dir: ./dist/backups/local
  s3:
    backend: restic

jobs:
  nextcloud:
    recipe: nextcloud
    backup-to: [local, s3]
  paperless:
    recipe: paperless
    backup-to: [s3] # only to s3
  test:
    recipe: internal-code
    backup-to: [local]
