version: 1

secrets:
  localResticPassword:
    literal: supersecret

destinations:
  local:
    backend: rsync
    options:
      destination-dir: ./dist/backups/local
  s3:
    backend: restic
  local-restic:
    backend: restic
    options:
      repo: ./dist/backups/restic-local
      env:
        RESTIC_PASSWORD: '{{ .Secrets.localResticPassword }}'

jobs:
  nextcloud:
    recipe: nextcloud
    backup-to: [local, s3]
  paperless:
    recipe: paperless
    backup-to: [s3] # only to s3
  test:
    recipe: examples
    backup-to: [local]
  test-restic:
    recipe: examples
    backup-to: [local-restic]
