version: 1

backends:
  restic:
    enable: true
  rsync:
    enable: true

destinations:
  local:
    backend: rsync
  s3:
    backend: restic

jobs:
  nextcloud:
    recipe: nextcloud
    backup-to: [local, s3]
  paperless:
    recipe: paperless
    backup-to: [s3] # only to s3
