// Code generated by mockery. DO NOT EDIT.

package internal

import (
	proto "github.com/dotboris/standard-backups/pkg/proto"
	mock "github.com/stretchr/testify/mock"
)

// MockbackupClient is an autogenerated mock type for the backupClient type
type MockbackupClient struct {
	mock.Mock
}

type MockbackupClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockbackupClient) EXPECT() *MockbackupClient_Expecter {
	return &MockbackupClient_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function with given fields: req
func (_m *MockbackupClient) Backup(req *proto.BackupRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*proto.BackupRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockbackupClient_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type MockbackupClient_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - req *proto.BackupRequest
func (_e *MockbackupClient_Expecter) Backup(req interface{}) *MockbackupClient_Backup_Call {
	return &MockbackupClient_Backup_Call{Call: _e.mock.On("Backup", req)}
}

func (_c *MockbackupClient_Backup_Call) Run(run func(req *proto.BackupRequest)) *MockbackupClient_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*proto.BackupRequest))
	})
	return _c
}

func (_c *MockbackupClient_Backup_Call) Return(_a0 error) *MockbackupClient_Backup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockbackupClient_Backup_Call) RunAndReturn(run func(*proto.BackupRequest) error) *MockbackupClient_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbackupClient creates a new instance of MockbackupClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbackupClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockbackupClient {
	mock := &MockbackupClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
