name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: extractions/setup-just@v3
      - run: just build-all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: extractions/setup-just@v3
      - run: just test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Use nix because it installs backup tools for us
      - uses: cachix/install-nix-action@v31
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop -L -c just e2e

  check-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Use nix because it installs `mockery` for us
      - uses: cachix/install-nix-action@v31
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop -L -c just generate-mocks
      - run: git diff --color=always --exit-code
